name: ðŸ³ Build & Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ðŸ³ Build apps
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      pushout: ${{ github.run_number }}
    env:
      BASE_IMAGE: "ghcr.io/sugar-space/web-lisk"
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ghcr.io/${{ env.APPS_CONTAINER }}
      #     tags: |
      #       type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # - name: Semantic Version bump
      #   if: inputs.version != ''
      #   id: version-bump
      #   run: |
      #     echo "NEW_VERSION=$(npm --no-git-tag-version version ${{ inputs.version }})" >> $GITHUB_OUTPUT

      # - name: Git commit and push the semver bump
      #   if: inputs.version != ''
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add package.json package-lock.json
      #     git commit -m "[skip actions] version bump to ${{ steps.version-bump.outputs.NEW_VERSION }}"
      #     git push

      - name: Search and replace value in ENV
        run: |
          echo "not such a secret; just avoiding harcoded .env"
          echo -e 'VITE_BE_URL="https://api.sugarhub.space"' >> .env
          echo -e 'VITE_WS_URL="wss://api.sugarhub.space"' >> .env

      - name: debug
        run: |
          ls -la

      - name: Build and push
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ env.BASE_IMAGE }}:latest,${{ env.BASE_IMAGE }}:${{ github.run_number }}

  deploy-prod:
    name: Web to Production
    if: |
      success() &&
      (github.ref == 'refs/heads/main') &&
      (github.event_name != 'workflow_dispatch')
    needs: [build]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: "production"
      environment-url: "https://sugarhub.space/"
      nomad-directory: ".deployment/nomad"
      nomad-job: "prod.hcl"
      nomad-addr: "https://nomad.sugarhub.space"
      image-tag: ${{ needs.build.outputs.pushout }}
      module: "web"
      semver-type: minor
    secrets: inherit
